version: '3.8'

services:
  ml:
    build:
      context: ../  # project root
      dockerfile: docker/ml/Dockerfile
    container_name: ml-service
    ports:
      - "5000:5000"
    environment:
      - TZ=UTC
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_API_KEY_2=${GEMINI_API_KEY_2}
      - LOCAL_ENDPOINT_LOV=${LOCAL_ENDPOINT_LOV}
    restart: unless-stopped

  kgsum-frontend:
    build:
      context: ../  # project root
      dockerfile: docker/web/Dockerfile
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:-}
        CLERK_SECRET_KEY: ${CLERK_SECRET_KEY:-}
    container_name: kgsum-frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - PORT=80
      - TZ=UTC
      - BUILD_DATE=2025-06-28 13:53:17
      - BUILD_USER=mariocosenza
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:-}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY:-}
    restart: unless-stopped
    user: "0:0"
    labels:
      - "maintainer=mariocosenza"
      - "build.date=2025-06-28 13:53:17"
      - "version=latest"
      - "project=kgsum-frontend"
    depends_on:
      - ml